- united_knitting_mills/ukm/biometric_backup/employee_checkin.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.json
**Biometric Integration Buffer Time and IN & OUT Sequencing**
> biometric-core changes

- united_knitting_mills/ukm/biometric_backup/employee_checkin.py
> Doctype name changed

- united_knitting_mills/ukm/biometric_backup/employee_checkin.py
> chores:else condition

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/biometric_backup/employee_checkin.py
- united_knitting_mills/ukm/utils/python/employee.py
Bio-metric Employee Number Unit wise
> Chandana employee number

- united_knitting_mills/ukm/utils/javascript/employee.js
Name fetching from employee doctype to salary structure assignment doctype
> employee name fetching

- united_knitting_mills/after_install.py
- united_knitting_mills/ukm/utils/python/salary_assignment_workflow.py
- united_knitting_mills/ukm/utils/python/workflow.py
> Workflow for salary structure and assignment

- united_knitting_mills/after_install.py
- united_knitting_mills/ukm/custom_fields/hr/employee_bonus_tool.py
- united_knitting_mills/ukm/custom_fields/hr/united_knitting_mills_settings.py
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.js
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
United Knitting Mills Settings - Add Bonus  Percentage Field
Employee Bonus Tool - Calculate the Employee Bonus For Employee Present Days
> Bonus amount

- united_knitting_mills/after_install.py
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
> chores:small fixes

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/utils/javascript/journal_entry.js
> Journal entry location fetching

- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.js
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
- united_knitting_mills/ukm/utils/javascript/journal_entry.js
small fixes in employee bonus tool
> chores : small fixes in employee bonus tool

- united_knitting_mills/ukm/doctype/thirvu_shift/thirvu_shift.py
> quarter shift

- united_knitting_mills/ukm/biometric_backup/employee_checkin.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.json
Note: Create test employee and single checkin entry for returning statement
> start-date checkin

- united_knitting_mills/ukm/custom_fields/assets/location.py
- united_knitting_mills/ukm/doctype/thirvu_location_user/thirvu_location_user.json
- united_knitting_mills/ukm/doctype/thirvu_location_user/thirvu_location_user.py
- united_knitting_mills/ukm/utils/javascript/journal_entry.js
- united_knitting_mills/ukm/utils/python/journal_entry.py
- united_knitting_mills/ukm/utils/python/location.py
Journal entry filter for location
> Filter:Journal entry filter

- united_knitting_mills/ukm/doctype/thirvu_shift/thirvu_shift.js
- united_knitting_mills/ukm/doctype/thirvu_shift/thirvu_shift.json
- united_knitting_mills/ukm/doctype/thirvu_shift/thirvu_shift.py
- united_knitting_mills/ukm/utils/python/attendance.py
> shift development

- united_knitting_mills/after_install.py
- united_knitting_mills/ukm/custom_fields/hr/designation.py
- united_knitting_mills/ukm/doctype/thirvu_shift/thirvu_shift.py
- united_knitting_mills/ukm/utils/python/attendance.py
First in and last out attendance
> First in and last out attendance

- united_knitting_mills/ukm/custom_fields/hr/designation.py
- united_knitting_mills/ukm/doctype/thirvu_shift/thirvu_shift.py
- united_knitting_mills/ukm/utils/python/attendance.py
> Shift Count

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/attendance.py
- united_knitting_mills/ukm/custom_fields/hr/employee.py
- united_knitting_mills/ukm/custom_fields/payroll/payroll_entry.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/report/decision_making___checkin_missing/decision_making___checkin_missing.js
- united_knitting_mills/ukm/report/decision_making___checkin_missing/decision_making___checkin_missing.json
- united_knitting_mills/ukm/report/decision_making___checkin_missing/decision_making___checkin_missing.py
- united_knitting_mills/ukm/report/decision_making___insufficient_working_hours/decision_making___insufficient_working_hours.json
- united_knitting_mills/ukm/utils/javascript/payroll_entry.js
- united_knitting_mills/ukm/utils/python/attendance.py
- united_knitting_mills/ukm/utils/python/employee.py
- united_knitting_mills/ukm/utils/python/employee__checkin.py
> changes-requirements

- united_knitting_mills/ukm/custom_fields/hr/attendance.py
- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.js
- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.json
- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.py
> Daily Attendance Report

- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
> fix in line supervisor

- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.html
- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.py
> report fix

- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.html
- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.js
- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.json
- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.py
- united_knitting_mills/ukm/report/wages_for_monthly_paid_workers/wages_for_monthly_paid_workers.js
- united_knitting_mills/ukm/report/wages_for_monthly_paid_workers/wages_for_monthly_paid_workers.json
- united_knitting_mills/ukm/report/wages_for_monthly_paid_workers/wages_for_monthly_paid_workers.py
> employee checkin report

- united_knitting_mills/ukm/utils/javascript/journal_entry.js
- united_knitting_mills/ukm/workspace/hr_cycle/hr_cycle.json
> fix in journal enrty

- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.html
- united_knitting_mills/ukm/report/daily_attendance_report/daily_attendance_report.py
- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.py
- united_knitting_mills/ukm/report/wages_for_monthly_paid_workers/wages_for_monthly_paid_workers.html
- united_knitting_mills/ukm/report/wages_for_monthly_paid_workers/wages_for_monthly_paid_workers.json
- united_knitting_mills/ukm/report/wages_for_monthly_paid_workers/wages_for_monthly_paid_workers.py
> Wages Report

- united_knitting_mills/after_install.py
- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/employee_advance.py
- united_knitting_mills/ukm/utils/javascript/salary_structure_assignment_list.js
- united_knitting_mills/ukm/utils/python/employee__checkin.py
- united_knitting_mills/ukm/utils/python/salary_assignment_workflow.py
- united_knitting_mills/ukm/workspace/hr_cycle/hr_cycle.json
> live site changes

- united_knitting_mills/ukm/doctype/employee_bonus/employee_bonus.json
- united_knitting_mills/ukm/doctype/employee_bonus/employee_bonus.py
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.js
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.json
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
> Chores:Employee Bonus fix

- united_knitting_mills/after_install.py
- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/employee_advance.py
- united_knitting_mills/ukm/custom_fields/hr/leave_application.py
- united_knitting_mills/ukm/utils/javascript/employee_advance.js
- united_knitting_mills/ukm/utils/javascript/employee_advance_list.js
- united_knitting_mills/ukm/utils/python/additional_salary.py
- united_knitting_mills/ukm/utils/python/employee_advance.py
Employe Advance and leave application customization
> leave application customization

- united_knitting_mills/ukm/utils/python/employee__checkin.py
> try pass for checkin

- united_knitting_mills/ukm/report/salary_slip/salary_slip.js
- united_knitting_mills/ukm/report/salary_slip/salary_slip.json
- united_knitting_mills/ukm/report/salary_slip/salary_slip.py
> salary slip report

- united_knitting_mills/ukm/custom_fields/hr/employee.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.json
- united_knitting_mills/ukm/report/salary_details_report/salary_details_report.py
> label change in salary report

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/utils/python/payroll_entry.py
fix for payrollentry and staff shift
> fix for payrollentry and staff shift

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/payroll_entry.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/utils/python/payroll_entry.py
> Payroll entry issuse

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/employee.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/utils/python/attendance.py
- united_knitting_mills/ukm/utils/python/leave_application.py
<google-sheets-html-origin>
Doctype | Description
-- | --
Employee | Holiday List field Mandatory.
Leave Application | After attendance creation, if leave application created or approved that should be affected in that attendance.
Attendance | While saving the document for approval, it will set some value for shift count, amount to pay, total minutes worked.
> Issues & Changes

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.json
- united_knitting_mills/ukm/utils/python/leave_application.py
<google-sheets-html-origin>
Doctype | Description
-- | --
Leave Application | For Permission Leave type total count and per application time should be validated.
> leave application -> permission leave type updation

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/employee_advance.py
- united_knitting_mills/ukm/doctype/employee_advance_details/employee_advance_details.json
- united_knitting_mills/ukm/doctype/employee_advance_tool/employee_advance_tool.js
- united_knitting_mills/ukm/doctype/employee_advance_tool/employee_advance_tool.json
- united_knitting_mills/ukm/doctype/employee_advance_tool/employee_advance_tool.py
- united_knitting_mills/ukm/doctype/ts_advance_validation/ts_advance_validation.json
- united_knitting_mills/ukm/doctype/ts_advance_validation/ts_advance_validation.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.json
- united_knitting_mills/ukm/utils/python/employee_advance.py
<google-sheets-html-origin>
Doctype | Description
-- | --
Employee Advance Tool | Need to create the advance amount for an employee by eligible salary. eg: eligible salary is 800 and current advance is 500 if eligible salary is 1300 and current advance is 1000.
Employee Advance Tool | Not allowed to change the current advance amount for any user.
Employee Advance Tool | Submit automatically need not to verify by the owner.
> Advance Calculation

- united_knitting_mills/ukm/custom_fields/hr/attendance.py
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.js
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.json
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/doctype/ts_bonus_validation/ts_bonus_validation.json
- united_knitting_mills/ukm/doctype/ts_bonus_validation/ts_bonus_validation.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.json
- united_knitting_mills/ukm/report/decision_making_(house_keeping)___breaktime_overconsumed/decision_making_(house_keeping)___breaktime_overconsumed.json
- united_knitting_mills/ukm/report/decision_making_(house_keeping)___checkin_missing/decision_making_(house_keeping)___checkin_missing.json
- united_knitting_mills/ukm/report/decision_making_(house_keeping)___early_exit/decision_making_(house_keeping)___early_exit.json
- united_knitting_mills/ukm/report/decision_making_(house_keeping)___insufficient_working_hours/decision_making_(house_keeping)___insufficient_working_hours.json
- united_knitting_mills/ukm/report/decision_making_(house_keeping)___late_entry/decision_making_(house_keeping)___late_entry.json
Employee Bonus Tool Development
> Bonus tool

- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.js
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.json
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
Employee bonus Tool Department Wise
> Department

- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/report/salary_details_report/salary_details_report.py
- united_knitting_mills/ukm/utils/python/salary_slip.py
> salry_details_report

- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.html
- united_knitting_mills/ukm/report/employee_checkin_report/employee_checkin_report.py
> Checkin report

- united_knitting_mills/patches.txt
- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.py
- united_knitting_mills/ukm/utils/python/employee__checkin.py
> Attendance recreation

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/custom_fields/hr/employee.py
- united_knitting_mills/ukm/doctype/employee_bank_details/employee_bank_details.js
- united_knitting_mills/ukm/doctype/employee_bank_details/employee_bank_details.json
- united_knitting_mills/ukm/doctype/employee_bank_details/employee_bank_details.py
- united_knitting_mills/ukm/doctype/employee_bank_details/test_employee_bank_details.py
- united_knitting_mills/ukm/utils/python/workflow.py
Employee Bank Details Doc and Workflow Development
> employee_bank_details_workflow

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/doctype/attendance_shift_changes/attendance_shift_changes.js
- united_knitting_mills/ukm/doctype/attendance_shift_changes/attendance_shift_changes.json
- united_knitting_mills/ukm/doctype/attendance_shift_changes/attendance_shift_changes.py
- united_knitting_mills/ukm/doctype/attendance_shift_changes/test_attendance_shift_changes.py
- united_knitting_mills/ukm/utils/javascript/attendance.js
- united_knitting_mills/ukm/utils/python/workflow.py
Attendance Shift Changes and Workflow Development
> attendance_shift_changes

- united_knitting_mills/hooks.py
- united_knitting_mills/ukm/doctype/employee_advance_tool/employee_advance_tool.py
- united_knitting_mills/ukm/utils/python/additional_salary.py
- united_knitting_mills/ukm/utils/python/employee_advance.py
Employee Advance, Additional salary, Payment Entry, Employee Advance Tool Delete Cancel Development
> cancel_delete_employee_advance_tool

- united_knitting_mills/ukm/report/costing_report/costing_report.js
- united_knitting_mills/ukm/report/costing_report/costing_report.json
- united_knitting_mills/ukm/report/costing_report/costing_report.py
> feat: costing report customization

- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
Odd Checkin with Shift Count and Attendance Present Status
> attendance_oddcheckin_present

- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
Staff Attendance Break Time Calculation from minutes
> staff_attendance_break_time

- united_knitting_mills/ukm/report/monthly_attendance_report/monthly_attendance_report.js
- united_knitting_mills/ukm/report/monthly_attendance_report/monthly_attendance_report.json
- united_knitting_mills/ukm/report/monthly_attendance_report/monthly_attendance_report.py
> feat:attendance report

- united_knitting_mills/ukm/report/monthly_attendance_report/monthly_attendance_report.js
- united_knitting_mills/ukm/report/monthly_attendance_report/monthly_attendance_report.py
> report added fields

- united_knitting_mills/ukm/doctype/employee_timing_details/employee_timing_details.py
- united_knitting_mills/ukm/utils/python/employee__checkin.py
> shift_calcc

- united_knitting_mills/ukm/doctype/employee_salary_details/employee_salary_details.py
- united_knitting_mills/ukm/report/employee_bonus_details_report/employee_bonus_details_report.py
- united_knitting_mills/ukm/report/employee_bonus_report/employee_bonus_report.py
> emp_bonus_details

- united_knitting_mills/ukm/doctype/employee_bonus/employee_bonus.json
- united_knitting_mills/ukm/doctype/employee_bonus_details/employee_bonus_details.json
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.js
- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
- united_knitting_mills/ukm/report/employee_bonus_report/employee_bonus_report.js
- united_knitting_mills/ukm/report/employee_bonus_report/employee_bonus_report.py
- united_knitting_mills/ukm/report/employee_bonus_report___staff/employee_bonus_report___staff.js
- united_knitting_mills/ukm/report/employee_bonus_report___staff/employee_bonus_report___staff.json
- united_knitting_mills/ukm/report/employee_bonus_report___staff/employee_bonus_report___staff.py
> staff_bonus

- united_knitting_mills/ukm/doctype/employee_bonus_tool/employee_bonus_tool.py
- united_knitting_mills/ukm/doctype/employee_salary_details/employee_salary_details.json
- united_knitting_mills/ukm/doctype/employee_salary_details/employee_salary_details.py
- united_knitting_mills/ukm/report/salary_details_report/salary_details_report.js
- united_knitting_mills/ukm/report/salary_details_report/salary_details_report.py
> bonus_tool_changes

- united_knitting_mills/ukm/doctype/employee_commision/employee_commision.json
- united_knitting_mills/ukm/doctype/employee_commision/employee_commision.py
- united_knitting_mills/ukm/doctype/united_knitting_mills_settings/united_knitting_mills_settings.json
- united_knitting_mills/ukm/report/employee_commision_details_report/employee_commision_details_report.js
- united_knitting_mills/ukm/report/employee_commision_details_report/employee_commision_details_report.json
- united_knitting_mills/ukm/report/employee_commision_details_report/employee_commision_details_report.py
- united_knitting_mills/ukm/utils/javascript/employee.js
> employee_commision_report

- united_knitting_mills/ukm/report/employee_commission_details_report/employee_commission_details_report.js
- united_knitting_mills/ukm/report/employee_commission_details_report/employee_commission_details_report.py
> department _filter_adding
